# Generated by Django 6.0 on 2026-01-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=233)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='cours/')),
                ('is_active', models.BooleanField(default=False)),
                ('max_st', models.IntegerField(default=12)),
                ('cours_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_st_count', models.CharField(max_length=233)),
                ('now_st_count', models.CharField(max_length=233)),
                ('finish_st', models.CharField(max_length=233)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=233)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courseschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, max_length=233, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('room', models.CharField(max_length=233)),
                ('note', models.CharField(max_length=233)),
            ],
        ),
        migrations.CreateModel(
            name='Coursescheduleweek_days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_uz', models.CharField(max_length=233)),
                ('name_uzkr', models.CharField(max_length=233)),
                ('name_ru', models.CharField(max_length=233)),
                ('name_en', models.CharField(max_length=233)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=233)),
                ('description', models.CharField(blank=True, max_length=233, null=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('files', models.CharField(max_length=233)),
                ('is_exam', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_number', models.CharField(max_length=23)),
                ('title', models.CharField(max_length=233)),
                ('description', models.CharField(blank=True, max_length=233, null=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('files', models.CharField(max_length=233)),
                ('is_exam', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.CharField(max_length=233)),
                ('title', models.CharField(max_length=233)),
                ('description', models.CharField(blank=True, max_length=233, null=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('files', models.CharField(max_length=233)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonQuession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=233)),
                ('description', models.CharField(blank=True, max_length=233, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=233)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LessonQuessionsQuession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=233)),
                ('description', models.CharField(blank=True, max_length=233, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('duration', models.CharField(max_length=233)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionsAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=233)),
                ('image', models.ImageField(blank=True, upload_to='media/')),
                ('is_active', models.BooleanField(default=False)),
                ('is_true', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=233)),
                ('spent_time', models.DurationField()),
                ('is_first_time', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsAttance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_student_here', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=233)),
                ('ai_feedback', models.CharField(max_length=300)),
                ('is_teacher_checked', models.BooleanField(default=False)),
                ('teacher_star', models.CharField(max_length=233)),
                ('add_coin', models.CharField(max_length=233)),
                ('files', models.CharField(max_length=233)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
