# Generated by Django 6.0 on 2026-01-07 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('group', '0002_initial'),
        ('student', '0001_initial'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cours',
            name='cours_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.coursecategory'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='day_of_week',
            field=models.ManyToManyField(to='course.coursescheduleweek_days'),
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
        migrations.AddField(
            model_name='lessonmodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.cours'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_modul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lessonmodule'),
        ),
        migrations.AddField(
            model_name='lessonquession',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
        migrations.AddField(
            model_name='lessonquessionsquession',
            name='lesson_quession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lessonquession'),
        ),
        migrations.AddField(
            model_name='questionsanswer',
            name='lesson_questions_quesrion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lessonquessionsquession'),
        ),
        migrations.AddField(
            model_name='studentrate',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lessonquession'),
        ),
        migrations.AddField(
            model_name='studentrate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='studentsattance',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group'),
        ),
        migrations.AddField(
            model_name='studentsattance',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
        migrations.AddField(
            model_name='studentsattance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='studentsattance',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
        migrations.AddField(
            model_name='studentshomework',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.homework'),
        ),
        migrations.AddField(
            model_name='studentshomework',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
